version: '3.8'

services:
  db:
    image: postgres:17
    container_name: disaster-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mani@2003
      POSTGRES_DB: disaster_prediction
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
