"""Added parameters extra

Revision ID: 30c60103a0bd
Revises: 79c70d5ca604
Create Date: 2024-12-09 16:04:28.747013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c60103a0bd'
down_revision = '79c70d5ca604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disaster_history', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('disaster_history', 'disaster_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('disaster_history', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('disaster_history', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('disaster_history', 'disaster_occurred',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disaster_history', 'disaster_occurred',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('disaster_history', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('disaster_history', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('disaster_history', 'disaster_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('disaster_history', 'timestamp')
    # ### end Alembic commands ###
