"""empty message

Revision ID: 3d005edf1bd4
Revises: c3b92c894358
Create Date: 2024-12-12 11:38:25.884888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d005edf1bd4'
down_revision = 'c3b92c894358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
