"""empty message

Revision ID: 425cf44c24d4
Revises: 723b7bfcf906
Create Date: 2024-12-07 21:08:27.983985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425cf44c24d4'
down_revision = '723b7bfcf906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
