"""message

Revision ID: 51e041b5771b
Revises: 5c48fd764f44
Create Date: 2024-12-12 16:25:16.306017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e041b5771b'
down_revision = '5c48fd764f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
