"""all new changes

Revision ID: 5c48fd764f44
Revises: 30c60103a0bd
Create Date: 2024-12-09 19:50:03.411208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c48fd764f44'
down_revision = '30c60103a0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disaster_history', sa.Column('type_confidence', sa.Float(), nullable=True))
    op.add_column('disaster_history', sa.Column('possible_deaths', sa.Float(), nullable=True))
    op.add_column('disaster_history', sa.Column('infrastructure_loss', sa.Float(), nullable=True))
    op.drop_column('disaster_history', 'date')
    op.drop_column('disaster_history', 'confidence')
    op.drop_column('disaster_history', 'rainfall')
    op.drop_column('disaster_history', 'prediction')
    op.drop_column('disaster_history', 'description')
    op.drop_column('disaster_history', 'disaster_occurred')
    op.drop_column('disaster_history', 'temperature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disaster_history', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('disaster_history', sa.Column('disaster_occurred', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('disaster_history', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('disaster_history', sa.Column('prediction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('disaster_history', sa.Column('rainfall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('disaster_history', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('disaster_history', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('disaster_history', 'infrastructure_loss')
    op.drop_column('disaster_history', 'possible_deaths')
    op.drop_column('disaster_history', 'type_confidence')
    # ### end Alembic commands ###
