"""empty message

Revision ID: 6ab2a197ab0c
Revises: 
Create Date: 2024-12-06 02:26:35.071153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab2a197ab0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disaster_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disaster_history_id'), 'disaster_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disaster_history_id'), table_name='disaster_history')
    op.drop_table('disaster_history')
    # ### end Alembic commands ###
