"""Initial migration

Revision ID: 723b7bfcf906
Revises: 6ab2a197ab0c
Create Date: 2024-12-06 02:33:34.313468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723b7bfcf906'
down_revision = '6ab2a197ab0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
