"""empty message

Revision ID: 7b7b70a331ea
Revises: ba4d4ad6d40e
Create Date: 2024-12-08 23:35:38.373766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7b70a331ea'
down_revision = 'ba4d4ad6d40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
