"""new

Revision ID: ba4d4ad6d40e
Revises: 723b7bfcf906
Create Date: 2024-12-08 23:32:41.399949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4d4ad6d40e'
down_revision = '723b7bfcf906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disaster_history', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('disaster_history', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('disaster_history', sa.Column('rainfall', sa.Float(), nullable=True))
    op.add_column('disaster_history', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('disaster_history', sa.Column('disaster_occurred', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disaster_history', 'disaster_occurred')
    op.drop_column('disaster_history', 'temperature')
    op.drop_column('disaster_history', 'rainfall')
    op.drop_column('disaster_history', 'longitude')
    op.drop_column('disaster_history', 'latitude')
    # ### end Alembic commands ###
