"""changed region to location

Revision ID: c79bdabb0c71
Revises: 7b7b70a331ea
Create Date: 2024-12-09 14:31:57.600177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79bdabb0c71'
down_revision = '7b7b70a331ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
